### ISSUE TITLE
Crashing when generating coral summary file using parallel processing

### ISSUE THREAD

**Issue by juddpatterson** [nationalparkservice/SER-SFCN-CoralDash#8]
I just tried to generate coral summary files for three of our parks and it seems to crash when attempting parallel processing. When I set it to a single processor I was able to create the SARI and BUIS files without issue. While creating the rds for VIIS the dashboard still crashed, but I did find an rds file that must have been saved just prior to the crash. I can share the csv files via email.

**Comment by ellenmonster** [comment]
Fixed! Not sure what I did differently though--I just had to install another package on my computer (weird)
